<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
   <!-- joint's limits -->
    <xacro:property name="high_limit" value="3.142"/>
    <xacro:property name="low_limit" value="-3.142"/>
    <xacro:property name="velocity" value="10.0"/>
    <xacro:property name="effort" value="10.0"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- Width, length, height = x,y,z -->
    <xacro:property name="chassis_length" value="0.2"/>
    <xacro:property name="chassis_width" value="0.15"/> 
    <xacro:property name="chassis_height" value="0.12"/> 

    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_length" value="0.02"/>

    <xacro:property name="gearbox_radius" value="0.055"/>
    <xacro:property name="gearbox_thickness" value="0.0738"/>

    <xacro:property name="imu_length" value="0.01"/>
    <xacro:property name="imu_width" value="0.01"/> 
    <xacro:property name="imu_height" value="0.01"/> 

    <xacro:property name="rod_length" value="0.008"/>
    <xacro:property name="rod_width" value="0.02"/> 
    <xacro:property name="rod_height" value="0.148"/>

    <!-- Masses -->

    <xacro:property name="chassis_mass" value="2.0"/>
    <xacro:property name="rod_mass" value="0.1"/>
    <xacro:property name="wheel_mass" value="0.5"/>
    <xacro:property name="gearbox_mass" value="0.3"/>
    <xacro:property name="imu_mass" value="0.001"/>

    <!-- Offsets -->

    <xacro:property name="chassis_offset_x" value="0"/>
    <xacro:property name="chassis_offset_y" value="0"/>
    <xacro:property name="chassis_offset_z" value="0"/>

    <xacro:property name="imu_offset_x" value="0"/>
    <xacro:property name="imu_offset_y" value="0"/>
    <xacro:property name="imu_offset_z" value="0"/>

    <xacro:property name="gearbox_offset_x" value="0"/>
    <xacro:property name="gearbox_offset_y" value="${chassis_width/2 + gearbox_thickness/2}"/>
    <xacro:property name="gearbox_offset_z" value="0"/>

    <xacro:property name="hip_offset_x" value="${-rod_height}"/>
    <xacro:property name="hip_offset_y" value="0"/>
    <xacro:property name="hip_offset_z" value="${gearbox_thickness/2 + rod_length/2}"/>

    <xacro:property name="knee_offset_x" value="0"/>
    <xacro:property name="knee_offset_y" value="0"/>
    <xacro:property name="knee_offset_z" value="${motor_thickness/2 + rod_length/2}"/>

    <xacro:property name="wheel_offset_x" value="${knee_rod_length/2 + wheel_length/2} "/>
    <xacro:property name="wheel_offset_y" value="0"/>
    <xacro:property name="wheel_offset_z" value="${knee_rod_height}"/>
    

</robot>
