<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name='werdna'>

    <xacro:include filename="consts.xacro"/>  
    <xacro:include filename='inertial_macros.xacro'/>

    <!-- Chassis -->
    <link name="base_link">
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
        <visual>
            <origin xyz="${chassis_offset_x} ${chassis_offset_y} ${chassis_offset_z}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${chassis_offset_x} ${chassis_offset_y} ${chassis_offset_z}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </collision>
    </link>

    <!-- imu -->
    <!-- <link name="imu_link"></link> -->

    <!-- imu joint -->
    <!-- <joint name="imu_joint" type="fixed">
        <origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint> -->

    <!-- Left Hip - Gearbox -->
    <link name="left_hip_motor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${gearbox_radius}" length="${gearbox_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${gearbox_radius}" length="${gearbox_thickness}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_cylinder mass="${gearbox_mass}" length="${gearbox_thickness}" radius="${gearbox_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_hip_motor_joint" type="revolute">
        <origin xyz="0.0 ${gearbox_offset_y} 0.0" rpy="${pi/2} -${pi/6} 0.0"/>
        <parent link="base_link"/>
        <child link="left_hip_motor_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <link name="left_hip_link">
        <visual>
             <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
             <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
             <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="left_hip_joint" type="fixed">
        <origin xyz="0.0 0 -${gearbox_thickness/2 + rod_length/2}" rpy="0 0 0"/>
        <parent link="left_hip_motor_link"/>
        <child link="left_hip_link"/>
    </joint>

    <link name="left_knee_link">
        <visual>
             <origin xyz="0 0 ${rod_height/2}" rpy="0.0 0 ${pi/2}"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
             <origin xyz="0 0 ${rod_height/2}" rpy="0 0 ${pi/2}"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
             <origin xyz="0 0 ${rod_height/2}" rpy="0 0 ${pi/2}"/>
        </xacro:inertial_box>
    </link>

    <joint name="left_knee_joint" type="revolute">
        <origin xyz="-${rod_height} 0 0" rpy="${pi/2} 0 ${pi/6}"/>
        <parent link="left_hip_link"/>
        <child link="left_knee_link"/>
        <axis xyz="0.0 -1.0 0.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="left_knee_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 -${rod_length/2 + wheel_length/2} ${rod_height}" rpy="${pi/2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

        <!-- Right Hip - Gearbox -->
    <link name="right_hip_motor_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${gearbox_radius}" length="${gearbox_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${gearbox_radius}" length="${gearbox_thickness}"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_cylinder mass="${gearbox_mass}" length="${gearbox_thickness}" radius="${gearbox_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_hip_motor_joint" type="revolute">
        <origin xyz="0.0 -${gearbox_offset_y} 0.0" rpy="${pi/2} -${pi/6} 0.0"/>
        <parent link="base_link"/>
        <child link="right_hip_motor_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <link name="right_hip_link">
        <visual>
             <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
             <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
             <origin xyz="-${rod_height/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="right_hip_joint" type="fixed">
        <origin xyz="0.0 0 ${gearbox_thickness/2 + rod_length/2}" rpy="0 0 0"/>
        <parent link="right_hip_motor_link"/>
        <child link="right_hip_link"/>
    </joint>

    <link name="right_knee_link">
        <visual>
             <origin xyz="0 0 ${rod_height/2}" rpy="0.0 0 ${pi/2}"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
             <origin xyz="0 0 ${rod_height/2}" rpy="0 0 ${pi/2}"/>
            <geometry>
                <box size="${rod_length} ${rod_width} ${rod_height}" rpy="0 0 0"/>
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:inertial_box mass="${rod_mass}" x="${rod_length}" y="${rod_width}" z="${rod_height}">
             <origin xyz="0 0 ${rod_height/2}" rpy="0 0 ${pi/2}"/>
        </xacro:inertial_box>
    </link>

    <joint name="right_knee_joint" type="revolute">
        <origin xyz="-${rod_height} 0 0" rpy="${pi/2} 0 ${pi/6}"/>
        <parent link="right_hip_link"/>
        <child link="right_knee_link"/>
        <axis xyz="0.0 -1.0 0.0"/>
        <limit lower="${low_limit}" upper="${high_limit}" velocity="${velocity}" effort="${effort}"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="right_knee_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${rod_length/2 + wheel_length/2} ${rod_height}" rpy="${pi/2} 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>
    
</robot>
