controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    wheel_controller:
      type: effort_controllers/JointGroupEffortController
      # type: velocity_controllers/JointGroupVelocityController

    odometry_broadcaster:
      type: werdna_odometry_broadcaster/WerdnaOdometryBroadcaster

#     imu_broadcaster:
#       type: imu_sensor_broadcaster/IMUSensorBroadcaster

# imu_broadcaster:
#   ros__parameters:
#     sensor_name: "imu_sensor"
#     frame_id:  "imu_sensor_frame"

position_controller:
  ros__parameters:
    joints:
      - left_hip_joint
      # - left_knee_joint
      - right_hip_joint
      # - right_knee_joint

wheel_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint

odometry_broadcaster:
  ros__parameters:
    publish_rate: 100.0

    left_wheel_names: left_wheel_joint
    right_wheel_names: right_wheel_joint

    wheel_separation: 0.2915

    wheel_radius: 0.0855
    
  